apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: workspaces-openshift-com-redirector
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      run: workspaces-openshift-com-redirector
    name: workspaces-openshift-com-redirector
  spec:
    replicas: ${{REPLICAS}}
    selector:
      run: workspaces-openshift-com-redirector
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: workspaces-openshift-com-redirector
      spec:
        containers:
        - env:
          - name: REDIRECTOR_DESTINATION
            valueFrom:
              configMapKeyRef:
                name: workspaces-openshift-com-redirector
                key: redirector.destination
          - name: REDIRECTOR_TYPE
            valueFrom:
              configMapKeyRef:
                name: workspaces-openshift-com-redirector
                key: redirector.type
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: redirector
          ports:
          - containerPort: 8080
            protocol: TCP
          terminationMessagePath: /dev/termination-log
          resources:
            requests:
              cpu: 20m
              memory: 10Mi
            limits:
              cpu: 40m
              memory: 40Mi
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: workspaces-openshift-com-redirector
  spec:
    ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      run: workspaces-openshift-com-redirector
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
- name: IMAGE
  value: "quay.io/openshiftio/rhel-base-nginx-redirector"
- name: IMAGE_TAG
  value: "latest"
- name: REPLICAS
  value: "1"
